server:
  port: 8082
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    username: postgres
    password: docker
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/KRYDEVDB
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

---
spring:
  profiles: qa
  datasource:
    username: postgres
    password: docker
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/KRYQAVDB
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

---
spring:
  profiles: prod
  datasource:
    username: postgres
    password: docker
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/KRYPRODVDB
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
