server:
  port: 8082
spring:
  profiles:
    active: dev
---
# Database settings (Database shifting can be done by changing tht properties below.)
spring:
  profiles: dev
  datasource:
    username: postgres
    password: docker
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/KRYDEVDB
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

#Settings for http response
kry:
  default:
    response: FAIL
    condition : PASS,FAIL

#Used to manage the DB anc cache.
schedule:
  dbsync:
    fixed:
      delay: 30000
    initial:
      delay: 5000
  http:
    fixed:
      delay: 20000
    initial:
      delay: 1000

#Validation rules messages
user:
  name:
    invalid: User name cannot be blank.

--- # Settings ------
#end points
management:
  endpoints:
    web:
      exposure:
        include: "*"
# ---Setting for loggin
#logging:
#  level:
#    root: INFO
#    org.springframework.web: DEBUG
#    com.howtodoinjava: DEBUG
#    org.hibernate: ERROR
