server:
  port: 8082
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    username: postgres
    password: docker
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/KRYDEVDB
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
schedule:
  fixed:
    delay: 40000

---
spring:
  profiles: qa
  datasource:
    username: postgres
    password: docker
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/KRYQAVDB
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  task:
    execution:
      pool:
        max-size: 1

---
spring:
  profiles: prod
  datasource:
    username: postgres
    password: docker
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/KRYPRODVDB
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

---
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.howtodoinjava: DEBUG
    org.hibernate: ERROR
---

user:
  name:
    invalid: User name cannot be blank.
