server:
  port: 8082
spring:
  profiles:
    active: mysql
---
# Database settings (Database shifting can be done by changing tht properties below.)
spring:
  profiles: postgres
  datasource:
    username: postgres
    password: docker
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/KRYDEVDB
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

---
spring:
  profiles: mysql
  datasource:
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/KRYDEVDB
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
---
spring:
  jpa:
    properties:
      hibernate:
        format_sql:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update

#Settings for http response
kry:
  default:
    response: FAIL
    condition : PASS,FAIL

#Used to manage the DB anc cache.
schedule:
  dbsync:
    fixed:
      delay: 30000
    initial:
      delay: 5000
  http:
    fixed:
      delay: 20000
    initial:
      delay: 1000

#Validation rules messages
user:
  name:
    invalid: User name cannot be blank.

--- # Settings ------
#end points
management:
  endpoints:
    web:
      exposure:
        include: "*"
# ---Setting for loggin
#logging:
#  level:
#    root: INFO
#    org.springframework.web: DEBUG
#    com.howtodoinjava: DEBUG
#    org.hibernate: ERROR
